# =============================================================================
# Kaizen — dev / prod compose shortcuts
# =============================================================================
# DEV  = base + docker-compose.dev.yml  → OPEN ports (local development/debug)
# PROD = base + docker-compose.prod.yml → CLOSED (no published ports) + log rotation
#
#   make up          # ONE command: start the DEV stack + approve agents in-terminal
#   make up dev      # same, explicit
#   make up prod     # ONE command: start the PROD stack (closed) + approve agents
#   make approve     # approve agents waiting to connect (Кая, Кузя, …)
#   make down [dev|prod]   # stop the chosen stack (default dev)
#   make logs [dev|prod]   # follow logs (all services)
#   make ps   [dev|prod]   # list services
#   make psql [dev|prod]   # open psql on Brain's DB
#   make e2e-secrets       # regenerate throwaway tokens for the e2e stand
#   make e2e-secrets-live  # same + verify .env.e2e.live.secrets is filled in
#   make e2e-up / e2e-down # bring up/down the isolated e2e stack (contract tier)
#   make e2e-up-flow       # same + fake-llm + the flow tier's kaya DB (§8)
#
# Every target takes the same optional [dev|prod] word — `make up prod` and
# `make down` used to operate on DIFFERENT project compositions (down ignored
# the overlays), which is why they all go through $(COMPOSE) now.
# =============================================================================

DEV  := docker compose --env-file .env -f deploy/docker-compose.yml -f deploy/docker-compose.dev.yml
PROD := docker compose --env-file .env -f deploy/docker-compose.yml -f deploy/docker-compose.prod.yml
# Own compose project (`name: kaizen-e2e` in the overlay itself) — isolated
# from DEV/PROD's containers, network and volumes, and reads ONLY the
# generated throwaway file, never the real .env (docs/e2e/README.md §8).
E2E      := docker compose --env-file .env.e2e.generated -f deploy/docker-compose.yml -f deploy/docker-compose.e2e.yml
E2E_FLOW := docker compose --env-file .env.e2e.generated -f deploy/docker-compose.yml -f deploy/docker-compose.e2e.yml -f deploy/docker-compose.e2e-flow.yml

# `make <target> [dev|prod]` — the word after the target selects the stack;
# default dev. The MODE word is also a (no-op) target below so make doesn't
# complain.
MODE := $(word 2,$(MAKECMDGOALS))
ifeq ($(MODE),)
MODE := dev
endif
ifeq ($(filter $(MODE),dev prod),)
$(error usage: make up [dev|prod] — got '$(MODE)')
endif
COMPOSE := $(if $(filter prod,$(MODE)),$(PROD),$(DEV))

.PHONY: up dev prod approve notify-selftest down logs ps psql migration migrate migration-status e2e-secrets e2e-secrets-live e2e-up e2e-down e2e-up-flow

# One command: bring the chosen stack up, then approve agents in the terminal.
up:
	@echo "Starting the $(MODE) stack…"
	$(COMPOSE) up -d --build
	@bash infra/scripts/approve.sh
	@echo "Done. If Кая is on the CLI backend, log in once: docker compose --env-file .env -f deploy/docker-compose.yml exec kaya claude"

# Argument words for `make up dev|prod` — no-ops on their own position.
dev prod:
	@:

approve:
	@bash infra/scripts/approve.sh

# "Is anything actually reaching me?" — sends a real event down the real path
# (module → Brain /event → agent → Telegram). The boot checks catch an empty or
# template MODULE_EVENT_TOKEN; this catches the other half, where both sides are
# set to DIFFERENT values and every report silently 401s.
notify-selftest:
	@bash infra/scripts/notify-selftest.sh

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f

ps:
	$(COMPOSE) ps

# Write a migration for one service after changing its models.
#   make migration svc=brain m="add purpose to project"
# Autogenerated by diffing the models against the RUNNING database, so the stack
# has to be up. Review the file it writes before committing — autogenerate is a
# good first draft and a bad final answer, especially for renames.
migration:
	@test -n "$(svc)" || (echo "usage: make migration svc=<brain|kaya> m=\"message\""; exit 1)
	@test -n "$(m)"   || (echo "a migration needs a message: m=\"what changed\""; exit 1)
	$(COMPOSE) exec -T $(svc) python -m infra.migrations revision $(svc) "$(m)"

# Apply pending migrations without restarting anything. Services also do this at
# boot; this is for applying one you just wrote.
migrate:
	$(COMPOSE) exec -T brain python -m infra.migrations upgrade --all

# Which revision each database is on.
migration-status:
	$(COMPOSE) exec -T brain python -m infra.migrations current --all

# Open psql on Brain's database.
psql:
	$(COMPOSE) exec -T postgres psql -U $${POSTGRES_USER:-learnbot} -d brain

# Regenerate throwaway e2e tokens into .env.e2e.generated (flow/contract
# tiers — no real credentials involved, see docs/e2e/README.md §8). The
# script is a project-agnostic kit export (also copied into every e2e-enabled
# project by infra/agentkit/render.py) — edit .env.e2e.generated.example, not
# the script, to change which keys Kaizen generates.
e2e-secrets:
	@python3 docs/e2e/host/e2e_gen_secrets.py

# Same, but also checks .env.e2e.live.secrets exists and has the expected
# keys — required for the manual `live` tier only (real Claude + real
# Telegram, never an auto gate).
e2e-secrets-live:
	@python3 docs/e2e/host/e2e_gen_secrets.py --live

# Bring up the isolated e2e stack (contract tier — postgres/brain/tracker/
# mentor/tools, no Кая/backup/kuzya, see deploy/docker-compose.e2e.yml).
# Tokens regenerate on every call, same as a fresh `make up`. --wait: without
# it this returns as soon as containers START, not once healthchecks pass —
# a test run launched immediately after would race brain's own boot.
e2e-up: e2e-secrets
	$(E2E) up -d --build --wait

# $(E2E_FLOW), not $(E2E): found by actually running this — `down` with only
# the contract-tier files has no idea the flow overlay's `fake-llm` exists,
# so it leaves that container running (and the network un-removable) whenever
# `make e2e-up-flow` was the one that started things. The superset of files
# is a safe no-op for a service that was never created.
e2e-down:
	$(E2E_FLOW) down

# Same stack plus fake-llm and the flow tier's `kaya` logical database
# (docs/e2e/README.md §8). No `kaya` container ever boots in this tier — the
# "real Кая" it drives is agents.core.Agent + agents/kaya/connector.py,
# constructed by the test process itself (see tests/e2e/flow/conftest.py) —
# so nothing creates+migrates kaya's DB the way a real kaya boot normally
# does. `exec -T brain` because brain's image is the same shared image every
# service builds from (deploy/docker/Dockerfile, context: ..) — it has
# agents.kaya's code even though it never runs it.
e2e-up-flow: e2e-secrets
	$(E2E_FLOW) up -d --build --wait
	$(E2E_FLOW) exec -T brain python -c "import asyncio; from agents.kaya.main import ensure_database; asyncio.run(ensure_database())"
	$(E2E_FLOW) exec -T brain python -m infra.migrations upgrade kaya


