# =============================================================================
# Kaizen — dev / prod compose shortcuts
# =============================================================================
# DEV  = base + docker-compose.dev.yml  → OPEN ports (local development/debug)
# PROD = base + docker-compose.prod.yml → CLOSED (no published ports) + log rotation
#
#   make up          # ONE command: start the DEV stack + approve agents in-terminal
#   make up dev      # same, explicit
#   make up prod     # ONE command: start the PROD stack (closed) + approve agents
#   make approve     # approve agents waiting to connect (Кая, …)
#   make down [dev|prod]   # stop the chosen stack (default dev)
#   make logs [dev|prod]   # follow logs (all services)
#   make ps   [dev|prod]   # list services
#   make psql [dev|prod]   # open psql on Brain's DB
#
# Every target takes the same optional [dev|prod] word — `make up prod` and
# `make down` used to operate on DIFFERENT project compositions (down ignored
# the overlays), which is why they all go through $(COMPOSE) now.
# =============================================================================

DEV  := docker compose --env-file .env -f deploy/docker-compose.yml -f deploy/docker-compose.dev.yml
PROD := docker compose --env-file .env -f deploy/docker-compose.yml -f deploy/docker-compose.prod.yml

# `make <target> [dev|prod]` — the word after the target selects the stack;
# default dev. The MODE word is also a (no-op) target below so make doesn't
# complain.
MODE := $(word 2,$(MAKECMDGOALS))
ifeq ($(MODE),)
MODE := dev
endif
ifeq ($(filter $(MODE),dev prod),)
$(error usage: make up [dev|prod] — got '$(MODE)')
endif
COMPOSE := $(if $(filter prod,$(MODE)),$(PROD),$(DEV))

.PHONY: up dev prod approve notify-selftest down logs ps psql migration migrate migration-status

# One command: bring the chosen stack up, then approve agents in the terminal.
up:
	@echo "Starting the $(MODE) stack…"
	$(COMPOSE) up -d --build
	@bash infra/scripts/approve.sh
	@echo "Done. If Кая is on the CLI backend, log in once: docker compose --env-file .env -f deploy/docker-compose.yml exec kaya claude"

# Argument words for `make up dev|prod` — no-ops on their own position.
dev prod:
	@:

approve:
	@bash infra/scripts/approve.sh

# "Is anything actually reaching me?" — sends a real event down the real path
# (module → Brain /event → agent → Telegram). The boot checks catch an empty or
# template MODULE_EVENT_TOKEN; this catches the other half, where both sides are
# set to DIFFERENT values and every report silently 401s.
notify-selftest:
	@bash infra/scripts/notify-selftest.sh

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f

ps:
	$(COMPOSE) ps

# Write a migration for one service after changing its models.
#   make migration svc=kaya m="add purpose to project"
# Autogenerated by diffing the models against the RUNNING database, so the stack
# has to be up. Review the file it writes before committing — autogenerate is a
# good first draft and a bad final answer, especially for renames.
migration:
	@test -n "$(svc)" || (echo "usage: make migration svc=<brain|kaya> m=\"message\""; exit 1)
	@test -n "$(m)"   || (echo "a migration needs a message: m=\"what changed\""; exit 1)
	$(COMPOSE) exec -T $(svc) python -m infra.migrations revision $(svc) "$(m)"

# Apply pending migrations without restarting anything. Services also do this at
# boot; this is for applying one you just wrote.
migrate:
	$(COMPOSE) exec -T brain python -m infra.migrations upgrade --all

# Which revision each database is on.
migration-status:
	$(COMPOSE) exec -T brain python -m infra.migrations current --all

# Open psql on Brain's database.
psql:
	$(COMPOSE) exec -T postgres psql -U $${POSTGRES_USER:-learnbot} -d brain


