"""add tunnel_messages table

Revision ID: 601863742ef2
Revises: cb572614b190
Created: 2026-08-08 09:40:52.500230
"""
from alembic import op
import sqlalchemy as sa


revision = '601863742ef2'
down_revision = 'cb572614b190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tunnel_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('directive_id', sa.BigInteger(), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('agent_slug', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brain_tunnel_messages_directive_created', 'tunnel_messages', ['directive_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brain_tunnel_messages_directive_created', table_name='tunnel_messages')
    op.drop_table('tunnel_messages')
    # ### end Alembic commands ###
