#!/usr/bin/env python3
"""WHAT: regenerates .env.e2e.generated from .env.e2e.generated.example, and
(with --live) verifies .env.e2e.live.secrets exists and has the expected keys.

WHY: project-agnostic e2e secrets split (docs/e2e/README.md §8) — every
project's e2e stand needs throwaway tokens regenerated on demand, plus a
separate file for real, spend-capped credentials that are never generated and
never read directly by an agent (see the project's own CLAUDE.md). Each
project defines its own keys, so this script knows none of them by name — it
only understands the GENERATE sentinel.

HOW: run from the repo root (the Makefile targets that call this already do).
Any `KEY=GENERATE` line in .env.e2e.generated.example gets a fresh random
token; any other value is copied through as-is — use that for fixed,
non-secret test config (a throwaway Postgres user, a fake Telegram id), not
real credentials. This script is a kit-owned export
(infra/agentkit/render.py's write_e2e_files): re-copied into every e2e-enabled
project on every render, never hand-edited in place.
"""
import argparse
import secrets
import sys
from pathlib import Path

GENERATED_EXAMPLE = Path(".env.e2e.generated.example")
GENERATED_OUT = Path(".env.e2e.generated")
LIVE_SECRETS = Path(".env.e2e.live.secrets")
LIVE_SECRETS_EXAMPLE = Path(".env.e2e.live.secrets.example")

GENERATE_SENTINEL = "GENERATE"


def parse_env_keys(path: Path) -> list[str]:
    keys = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        keys.append(line.split("=", 1)[0])
    return keys


def write_generated_env() -> None:
    if not GENERATED_EXAMPLE.exists():
        print(f"missing {GENERATED_EXAMPLE} — nothing to generate from.", file=sys.stderr)
        raise SystemExit(1)
    lines = ["# Auto-generated by docs/e2e/host/e2e_gen_secrets.py — do not edit by hand."]
    for line in GENERATED_EXAMPLE.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        value = secrets.token_urlsafe(32) if value == GENERATE_SENTINEL else value
        lines.append(f"{key}={value}")
    GENERATED_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {GENERATED_OUT}")


def check_live_secrets() -> bool:
    if not LIVE_SECRETS.exists():
        print(
            f"missing {LIVE_SECRETS} — the live tier needs real, spend-capped "
            f"credentials. Copy {LIVE_SECRETS_EXAMPLE} to {LIVE_SECRETS} and "
            f"fill it in by hand.",
            file=sys.stderr,
        )
        return False
    if LIVE_SECRETS_EXAMPLE.exists():
        missing = set(parse_env_keys(LIVE_SECRETS_EXAMPLE)) - set(parse_env_keys(LIVE_SECRETS))
        if missing:
            print(f"{LIVE_SECRETS} is missing key(s): {', '.join(sorted(missing))}", file=sys.stderr)
            return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--live",
        action="store_true",
        help="also verify .env.e2e.live.secrets exists and has the expected keys",
    )
    args = parser.parse_args()

    write_generated_env()

    if args.live and not check_live_secrets():
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
