"""baseline

Revision ID: bded3c3218c1
Revises: 
Created: 2026-08-02 03:23:32.457882
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bded3c3218c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('enroll_secret_hash', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('grpc_addr', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_projects_name'), 'tracker_projects', ['name'], unique=True)
    op.create_index(op.f('ix_tracker_projects_state'), 'tracker_projects', ['state'], unique=False)
    op.create_index(op.f('ix_tracker_projects_token'), 'tracker_projects', ['token'], unique=True)
    op.create_table('tracker_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('reports_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['tracker_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_agent_project_name')
    )
    op.create_index(op.f('ix_tracker_agents_project_id'), 'tracker_agents', ['project_id'], unique=False)
    op.create_table('tracker_directives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('auto_merge', sa.Boolean(), nullable=False),
    sa.Column('claimed_by', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tracker_directives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['tracker_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_directives_kind'), 'tracker_directives', ['kind'], unique=False)
    op.create_index(op.f('ix_tracker_directives_lease_expires_at'), 'tracker_directives', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_tracker_directives_parent_id'), 'tracker_directives', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tracker_directives_priority'), 'tracker_directives', ['priority'], unique=False)
    op.create_index(op.f('ix_tracker_directives_project_id'), 'tracker_directives', ['project_id'], unique=False)
    op.create_index(op.f('ix_tracker_directives_status'), 'tracker_directives', ['status'], unique=False)
    op.create_index(op.f('ix_tracker_directives_task_id'), 'tracker_directives', ['task_id'], unique=False)
    op.create_table('tracker_agent_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('directive_id', sa.Integer(), nullable=False),
    sa.Column('agent_slug', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directive_id'], ['tracker_directives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('directive_id', 'agent_slug', name='uq_status_directive_agent')
    )
    op.create_index(op.f('ix_tracker_agent_status_directive_id'), 'tracker_agent_status', ['directive_id'], unique=False)
    op.create_table('tracker_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('directive_id', sa.Integer(), nullable=False),
    sa.Column('agent_slug', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('suggested', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['directive_id'], ['tracker_directives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracker_questions_directive_id'), 'tracker_questions', ['directive_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_questions_directive_id'), table_name='tracker_questions')
    op.drop_table('tracker_questions')
    op.drop_index(op.f('ix_tracker_agent_status_directive_id'), table_name='tracker_agent_status')
    op.drop_table('tracker_agent_status')
    op.drop_index(op.f('ix_tracker_directives_task_id'), table_name='tracker_directives')
    op.drop_index(op.f('ix_tracker_directives_status'), table_name='tracker_directives')
    op.drop_index(op.f('ix_tracker_directives_project_id'), table_name='tracker_directives')
    op.drop_index(op.f('ix_tracker_directives_priority'), table_name='tracker_directives')
    op.drop_index(op.f('ix_tracker_directives_parent_id'), table_name='tracker_directives')
    op.drop_index(op.f('ix_tracker_directives_lease_expires_at'), table_name='tracker_directives')
    op.drop_index(op.f('ix_tracker_directives_kind'), table_name='tracker_directives')
    op.drop_table('tracker_directives')
    op.drop_index(op.f('ix_tracker_agents_project_id'), table_name='tracker_agents')
    op.drop_table('tracker_agents')
    op.drop_index(op.f('ix_tracker_projects_token'), table_name='tracker_projects')
    op.drop_index(op.f('ix_tracker_projects_state'), table_name='tracker_projects')
    op.drop_index(op.f('ix_tracker_projects_name'), table_name='tracker_projects')
    op.drop_table('tracker_projects')
    # ### end Alembic commands ###
