# =============================================================================
# Unit tests — agents/core/enroll.py (the agent-side pairing client)
# =============================================================================
# WHAT: EnrollmentClient against a fake Brain (a real local aiohttp server):
#       the enroll → poll (POST, secret in body) → claim → store flow, plus the
#       stored-token short-circuit and the rejection path.
# WHY: Step 4 moved /enroll/status from GET+query to POST+body — this pins the
#       client to the new contract (a silent GET regression would strand every
#       agent at "waiting for approval" forever).
# HOW: aiohttp.test_utils.TestServer; FileCredentialStore in tmp_path.
# =============================================================================

import pytest
from aiohttp import web
from aiohttp.test_utils import TestServer

from agents.core.enroll import EnrollmentClient, FileCredentialStore


class FakeBrain:
    """Scripted /enroll + /enroll/status endpoints recording what they saw."""

    def __init__(self, statuses):
        self._statuses = list(statuses)  # what /enroll/status returns, in order
        self.enroll_bodies = []
        self.status_requests = []  # (method, body) — the contract under test

    def app(self) -> web.Application:
        app = web.Application()
        app.router.add_post("/enroll", self._enroll)
        app.router.add_post("/enroll/status", self._status)
        return app

    async def _enroll(self, request: web.Request) -> web.Response:
        self.enroll_bodies.append(await request.json())
        return web.json_response({"status": "pending"})

    async def _status(self, request: web.Request) -> web.Response:
        body = await request.json()
        self.status_requests.append((request.method, body))
        return web.json_response(self._statuses.pop(0))


async def _client_for(brain: FakeBrain, tmp_path) -> tuple[EnrollmentClient, TestServer]:
    server = TestServer(brain.app())
    await server.start_server()
    store = FileCredentialStore(str(tmp_path / "token"))
    client = EnrollmentClient(
        str(server.make_url("/")), "kaya", "", store, poll_interval=0.01
    )
    return client, server


async def test_enroll_poll_claim_and_store(tmp_path):
    brain = FakeBrain([
        {"status": "pending"},
        {"status": "approved", "token": "tok-123"},
    ])
    client, server = await _client_for(brain, tmp_path)
    try:
        token = await client.obtain_token()
    finally:
        await server.close()
    assert token == "tok-123"
    # The token was persisted for the next boot.
    assert FileCredentialStore(str(tmp_path / "token")).load() == "tok-123"
    # The secret travelled in POST bodies only (the Step 4 contract).
    assert brain.enroll_bodies[0]["slug"] == "kaya"
    secret = brain.enroll_bodies[0]["secret"]
    assert secret  # non-empty, generated by the client
    for method, body in brain.status_requests:
        assert method == "POST"
        assert body == {"slug": "kaya", "secret": secret}


async def test_stored_token_short_circuits(tmp_path):
    store = FileCredentialStore(str(tmp_path / "token"))
    store.save("existing-tok")
    brain = FakeBrain([])
    client, server = await _client_for(brain, tmp_path)
    try:
        assert await client.obtain_token() == "existing-tok"
    finally:
        await server.close()
    assert brain.enroll_bodies == []  # never even asked Brain


async def test_rejection_raises(tmp_path):
    brain = FakeBrain([{"status": "rejected"}])
    client, server = await _client_for(brain, tmp_path)
    try:
        with pytest.raises(RuntimeError, match="rejected"):
            await client.obtain_token()
    finally:
        await server.close()
